Adding an option to disable monitoring of the route file
ParticularLabs/NServiceBus.FileBasedRouting pull request #24
Opened 2017-06-28 03:55 UTC by HEskandari

Resolves #22

2017-07-05 02:09 UTC, HEskandari commented
@timbussmann @SzymonPobiega Updated the PR. Please review at your convenience.

2017-07-05 04:54 UTC, SzymonPobiega commented on src/NServiceBus.FileBasedRouting/FileBasedRoutingConfigExtensions.cs
> +        public static void UseFileBasedRouting(this RoutingSettings config, TimeSpan? updateInterval = null)
This is a breaking change. Should we add an overload instead of an optional param to avoid it?

2017-07-05 04:55 UTC, SzymonPobiega submitted a review, later dismissed
One suggestion. Otherwise looks good.

2017-07-05 05:32 UTC, HEskandari commented on src/NServiceBus.FileBasedRouting/FileBasedRoutingConfigExtensions.cs
> +        public static void UseFileBasedRouting(this RoutingSettings config, TimeSpan? updateInterval = null)
Isn't the old API still available? Why is this a breaking change?

2017-07-05 06:27 UTC, SzymonPobiega commented on src/NServiceBus.FileBasedRouting/FileBasedRoutingConfigExtensions.cs
> +        public static void UseFileBasedRouting(this RoutingSettings config, TimeSpan? updateInterval = null)
@HEskandari because of the optional parameter. It is added on call-site.

2017-07-05 08:25 UTC, HEskandari commented on src/NServiceBus.FileBasedRouting/FileBasedRoutingConfigExtensions.cs
> +        public static void UseFileBasedRouting(this RoutingSettings config, TimeSpan? updateInterval = null)
@SzymonPobiega fair enough. I'll change them to normal overloads.

2017-07-05 08:39 UTC, timbussmann commented on src/NServiceBus.FileBasedRouting/FileBasedRoutingConfigExtensions.cs
> +        public static void UseFileBasedRouting(this RoutingSettings config, TimeSpan? updateInterval = null)
👍 for overload instead of optional parameter to avoid breaking changes.

2017-07-06 12:41 UTC, HEskandari commented
@SzymonPobiega @timbussmann Updated.

2017-07-07 06:18 UTC, timbussmann requested changes
one small detail. LGTM otherwise

2017-07-07 06:18 UTC, timbussmann commented on src/NServiceBus.FileBasedRouting/FileBasedRoutingFeature.cs
> +            var routeFileUpdateInterval = context.Settings.Get<TimeSpan?>(RouteFileUpdateInterval);
the value doesn't have to be nullable anymore I think?

2017-07-07 06:58 UTC, HEskandari commented on src/NServiceBus.FileBasedRouting/FileBasedRoutingFeature.cs
> +            var routeFileUpdateInterval = context.Settings.Get<TimeSpan?>(RouteFileUpdateInterval);
Good catch @timbussmann fixed.

2017-07-07 06:59 UTC, timbussmann approved these changes

2017-07-07 06:59 UTC, merged

2017-07-07 07:00 UTC, timbussmann commented
merging this as @SzymonPobiega and my comments have been addressed 👍